/* Family members. First names only. No emails. */
const PEOPLE = [
  {"id": "alex", "name": "Alex", "key": "DI", "shape": "blend", "code": "ISDCICDSISDCSCISDCDSICICISICDSDSISICDCICICISISICICDCDCDC", "likert": "442134215511341355211512", "N": {"D": 60, "I": 71, "S": 23, "C": 13}, "seg": {"D": 5, "I": 5, "S": 2, "C": 1}, "band": {"D": "Moderate", "I": "High", "S": "Low", "C": "Low"}, "order": ["I", "D", "S", "C"], "gap": 11, "spread": 58, "intensity": {"D": 3.5, "I": 4.5, "S": 1.5, "C": 1.5}, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=ISDCICDSISDCSCISDCDSICICISICDSDSISICDCICICISISICICDCDCDC&l=442134215511341355211512"},
  {"id": "derek", "name": "Derek", "key": "SC", "shape": "blend", "code": "CSSDCISCIDCDSDSICICICIDICICISDSISISISICIDSSDCIICCICICICS", "likert": null, "N": {"D": 31, "I": 18, "S": 54, "C": 64}, "seg": {"D": 3, "I": 2, "S": 4, "C": 5}, "band": {"D": "Low", "I": "Low", "S": "Moderate", "C": "Moderate"}, "order": ["C", "S", "D", "I"], "gap": 10, "spread": 46, "intensity": null, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=CSSDCISCIDCDSDSICICICIDICICISDSISISISICIDSSDCIICCICICICS"},
  {"id": "ashley", "name": "Ashley", "key": "DC", "shape": "blend", "code": "CIISSCDCIDDSICDSSICIISDSCICICDDIDCSDSDDICSSDSICSSIISCDSI", "likert": "453543254334534442544312", "N": {"D": 43, "I": 33, "S": 43, "C": 48}, "seg": {"D": 4, "I": 3, "S": 4, "C": 4}, "band": {"D": "Moderate", "I": "Low", "S": "Moderate", "C": "Moderate"}, "order": ["C", "D", "S", "I"], "gap": 5, "spread": 15, "intensity": {"D": 4.2, "I": 3.2, "S": 3.0, "C": 4.0}, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=CIISSCDCIDDSICDSSICIISDSCICICDDIDCSDSDDICSSDSICSSIISCDSI&l=453543254334534442544312"},
  {"id": "renee", "name": "Renee", "key": "SC", "shape": "blend", "code": "CISCCIDIICIDSICDDCCISICDIDCDSDDSCIDISDDIDIISCDSCCICISICD", "likert": "333422342454224544343422", "N": {"D": 37, "I": 27, "S": 48, "C": 55}, "seg": {"D": 3, "I": 2, "S": 4, "C": 4}, "band": {"D": "Moderate", "I": "Low", "S": "Moderate", "C": "Moderate"}, "order": ["C", "S", "D", "I"], "gap": 7, "spread": 28, "intensity": {"D": 2.7, "I": 3.2, "S": 3.3, "C": 3.8}, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=CISCCIDIICIDSICDDCCISICDIDCDSDDSCIDISDDIDIISCDSCCICISICD&l=333422342454224544343422"},
  {"id": "mike", "name": "Mike K", "key": "SC", "shape": "blend", "code": "CDIDSDDCIDIDICIDDCSDSICDCDDICDCISISIDISIICSCCIIDSIIDSDCD", "likert": null, "N": {"D": 26, "I": 42, "S": 55, "C": 44}, "seg": {"D": 2, "I": 3, "S": 4, "C": 4}, "band": {"D": "Low", "I": "Moderate", "S": "Moderate", "C": "Moderate"}, "order": ["S", "C", "I", "D"], "gap": 11, "spread": 29, "intensity": null, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=CDIDSDDCIDIDICIDDCSDSICDCDDICDCISISIDISIICSCCIIDSIIDSDCD"},
  {"id": "elliana", "name": "Elliana", "key": "balanced", "shape": "balanced", "code": "DSCDDSSCIDCDCDSDSISCSICSICDSSDCSDISIDCCDCIICISDSSDDSDSSC", "likert": null, "N": {"D": 43, "I": 37, "S": 44, "C": 43}, "seg": {"D": 4, "I": 3, "S": 4, "C": 4}, "band": {"D": "Moderate", "I": "Moderate", "S": "Moderate", "C": "Moderate"}, "order": ["S", "D", "C", "I"], "gap": 1, "spread": 7, "intensity": null, "note": "Youngest sitting in the set — a profile this young is still forming. Read this page as a snapshot of now, not a settled shape.", "report": "https://whatdrivesyou.vercel.app/#r=DSCDDSSCIDCDCDSDSISCSICSICDSSDCSDISIDCCDCIICISDSSDDSDSSC"},
  {"id": "sofia", "name": "Sofia", "key": "SC", "shape": "blend", "code": "CDSDCSSCISDSSISDCISCSICDSICIDCSISDDCSCCICDSDSIDICSDIIDCI", "likert": "224413543244253432542252", "N": {"D": 36, "I": 25, "S": 57, "C": 49}, "seg": {"D": 3, "I": 2, "S": 4, "C": 4}, "band": {"D": "Moderate", "I": "Low", "S": "Moderate", "C": "Moderate"}, "order": ["S", "C", "D", "I"], "gap": 8, "spread": 32, "intensity": {"D": 2.2, "I": 2.7, "S": 4.3, "C": 3.7}, "note": "Name was blank on the original. Alex said this is probably Sofia.", "report": "https://whatdrivesyou.vercel.app/#r=CDSDCSSCISDSSISDCISCSICDSICIDCSISDDCSCCICDSDSIDICSDIIDCI&l=224413543244253432542252"},
  {"id": "colin", "name": "Colin", "key": "S", "shape": "primary", "code": "CISICDSCCDSDSISDSCSDCICDSDSISISDCISISICDCISICDDISISICDCI", "likert": "115511344254114511442151", "N": {"D": 23, "I": 15, "S": 71, "C": 57}, "seg": {"D": 2, "I": 2, "S": 5, "C": 4}, "band": {"D": "Low", "I": "Low", "S": "High", "C": "Moderate"}, "order": ["S", "C", "D", "I"], "gap": 14, "spread": 56, "intensity": {"D": 1.7, "I": 1.2, "S": 4.3, "C": 3.8}, "note": null, "report": "https://whatdrivesyou.vercel.app/#r=CISICDSCCDSDSISDSCSDCICDSDSISISDCISISICDCISICDDISISICDCI&l=115511344254114511442151"},
  {"id": "kate", "name": "Kate", "key": "S", "shape": "primary", "code": "SCCDSCSCSDICSDSCSDSCIDCDICSCIDICCDCISCCDCISCCDSISCSDCISC", "likert": null, "N": {"D": 20, "I": 40, "S": 69, "C": 37}, "seg": {"D": 2, "I": 3, "S": 5, "C": 3}, "band": {"D": "Low", "I": "Moderate", "S": "High", "C": "Moderate"}, "order": ["S", "I", "C", "D"], "gap": 29, "spread": 49, "intensity": null, "note": "Rebuilt from her screenshot scores. Original answers never saved, so item picks are approximated. Intensity omitted because S and C were cut off.", "report": "https://whatdrivesyou.vercel.app/#r=SCCDSCSCSDICSDSCSDSCIDCDICSCIDICCDCISCCDCISCCDSISCSDCISC"},
  {"id": "cherie", "name": "Cherie", "key": "IS", "shape": "blend", "code": "ICICICSISIICSCSDICCSCISDSDIDIDIDISSCICIDSCSISCSISCIDICCI", "likert": "435355412434342233422441", "N": {"D": 24, "I": 57, "S": 60, "C": 26}, "seg": {"D": 2, "I": 4, "S": 5, "C": 2}, "band": {"D": "Low", "I": "Moderate", "S": "Moderate", "C": "Low"}, "order": ["S", "I", "C", "D"], "gap": 3, "spread": 36, "intensity": {"D": 3.2, "I": 3.8, "S": 3.7, "C": 2.2}, "note": "Derived, not a saved sitting. Alex rebuilt it after the two of them reviewed the picks where D read as restlessness rather than drive; her first recorded pass came out DI. Alex expects the real shape is more extreme still — almost no D or C.", "report": "https://whatdrivesyou.vercel.app/#r=ICICICSISIICSCSDICCSCISDSDIDIDIDISSCICIDSCSISCSISCIDICCI&l=435355412434342233422441"},
];
